#-------------------------------
# General Site Settings
title: YUXIN DENG
logo: logo.jpg # You can add own logo.
description: modern minimal theme by Jekyll inspired


#-------------------------------
# Author Settings
author:
  name: Yuxin Deng
  image: 01.jpg
  greeting: Iâ€™m <strong>Yuxin Deng</strong>, welcome to my secret world.
  bio: Designs, talks, and writes about <strong>web develop</strong>, <strong>technology</strong>, <strong>information security</strong>. Loves <a href="https://youtube.com/playlist?list=PLeb5S4wtUOpEePUWEEmVJqtGMVhvn5LWD">dance</a>, <a href="artworks/">photograph</a>, golf, snowboard.


#-------------------------------
# Contact links
#twitter: https://twitter.com/ # Add your Twitter handle
#facebook: https://www.facebook.com/yuxin.deng.5454 # Add your Facebook handle
linkedin: https://www.linkedin.com/in/yuxin-deng-a45627228/
github: https://github.com/yuxin-d
youtube: https://youtube.com/playlist?list=PLeb5S4wtUOpEePUWEEmVJqtGMVhvn5LWD
#dribbble: https://dribbble.com/ # Add your Dribbble handle
instagram: https://www.instagram.com/_irene_deng/ # Add your Instagram handle
#pinterest: https://pinterest.com/ # Add your Pinterest handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: ms-deng # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: false # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: _irene_deng # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
